# Generated by Django 3.1.1 on 2020-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('success', 'success'), ('failure', 'failure')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
